name: example
description: Example for using GraphQL Dart
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args:
  graphql:
    path: ..

executables:
  example: example
